"""
plan_runtime.py
---------------
This module executes a "plan" generated by an agent or planner model.

A plan is basically a JSON‑style recipe — a sequence of steps like:

{
  "steps": [
    {"tool": "group_count", "args": {"input": "df", "group_by": ["Agency"], "save_as": "by_agency"}},
    {"tool": "plot_line", "args": {"table": "by_agency", "x": "Agency", "y": "count", "title": "Launches per Agency", "out_path": "plots/by_agency.png"}},
    {"tool": "write_markdown", "args": {"title": "Agency Report", "tables": ["by_agency"], "out_path": "reports/agency_summary.md"}}
  ]
}

Each step tells us:
  - which tool to run (e.g. "group_count")
  - and what arguments to pass to that tool.

This runtime validates that structure, executes the tools sequentially,
and logs start/end events to the `state` object for traceability.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List

# Internal imports:
from core.state import log_event            # Utility for structured logging
from tools.analysis_tools import REGISTRY   # All known ToolSpec items from analysis_tools


# ---------------------------------------------------------------------
# PLAN VALIDATION
# ---------------------------------------------------------------------

def validate_plan(plan: Dict[str, Any]) -> None:
    """
    Check that the given plan is correctly formed before executing anything.

    Parameters
    ----------
    plan : Dict[str, Any]
        The plan to validate. Must look like: {"steps": [ { "tool": ..., "args": ... }, ... ] }

    Raises
    ------
    ValueError
        If the structure or contents of the plan are invalid.
    """
    # Basic type check — the whole plan must be a dictionary.
    if not isinstance(plan, dict):
        raise ValueError("Plan must be a JSON object.")

    # Ensure a "steps" key exists and is a list.
    if "steps" not in plan or not isinstance(plan["steps"], list):
        raise ValueError("Plan must have a 'steps' list.")

    # Validate each individual step.
    for i, step in enumerate(plan["steps"]):
        if not isinstance(step, dict):
            raise ValueError(f"Step {i} must be an object.")
        if "tool" not in step:
            raise ValueError(f"Step {i} missing 'tool'.")

        # Check that the tool name is actually defined in our tool registry.
        if step["tool"] not in REGISTRY:
            raise ValueError(f"Step {i} uses unknown tool '{step['tool']}'.")

        # The optional "args" key, if present, must itself be a dictionary.
        if "args" in step and not isinstance(step["args"], dict):
            raise ValueError(f"Step {i} 'args' must be an object.")


# ---------------------------------------------------------------------
# PLAN EXECUTION
# ---------------------------------------------------------------------

def execute_plan(*, state: Dict[str, Any], plan: Dict[str, Any], context: Dict[str, Any]) -> Dict[str, Any]:
    """
    Run a validated plan step by step.

    Tools are pulled dynamically from REGISTRY and mutate the shared `context` in-place.

    Parameters
    ----------
    state : Dict[str, Any]
        Holds runtime or logging information for the current analysis session.
        (Think of it as a black box where `log_event()` records what happened.)
    plan : Dict[str, Any]
        The full plan object with its "steps".
    context : Dict[str, Any]
        Shared workspace object where tools store intermediate results (same as in analysis_tools).

    Returns
    -------
    Dict[str, Any]
        The updated context after all steps are executed.
    """

    # Make sure the plan is valid before running.
    validate_plan(plan)

    steps: List[Dict[str, Any]] = plan["steps"]

    # Run steps sequentially (in the order they appear).
    for idx, step in enumerate(steps):
        tool_name = step["tool"]
        args = step.get("args", {})

        # Log that a step has started (for debugging or later replay).
        # _safe_args() cleans the argument data to avoid printing giant tables or dataframes.
        log_event(state, "plan.step.start", {"idx": idx, "tool": tool_name, "args": _safe_args(args)})

        # Fetch the ToolSpec for this tool and run its function.
        spec = REGISTRY[tool_name]

        # Call it: pass the shared context + all named arguments.
        spec.fn(context=context, **args)

        # Log step completion.
        log_event(state, "plan.step.end", {"idx": idx, "tool": tool_name})

    # Return the final context (which now has new tables, plots, etc.)
    return context


# ---------------------------------------------------------------------
# PLAN PARSING
# ---------------------------------------------------------------------

def parse_plan_json(text: str) -> Dict[str, Any]:
    """
    Parse a JSON string (for example, a raw LLM output) into a Python dictionary.

    The JSON is expected to describe a `plan` object conforming to the validation above.

    If parsing fails (e.g., badly formatted JSON), a ValueError is raised.

    Parameters
    ----------
    text : str
        JSON text of the plan.

    Returns
    -------
    Dict[str, Any]
        The parsed plan dictionary.
    """
    try:
        return json.loads(text)
    except Exception as e:
        raise ValueError(f"Failed to parse plan JSON: {e}") from e


# ---------------------------------------------------------------------
# HELPER: SAFE LOGGING OF ARGUMENTS
# ---------------------------------------------------------------------

def _safe_args(args: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return a sanitized copy of arguments for logging.

    Purpose
    -------
    Many tool arguments can be huge (like entire dataframes or long lists).
    We don't want to flood logs or accidentally leak data.

    This helper keeps only small, simple values and replaces large or complex
    data structures with a placeholder string (e.g., '<DataFrame>').

    Parameters
    ----------
    args : Dict[str, Any]
        Original arguments for a tool call.

    Returns
    -------
    Dict[str, Any]
        Cleaned-up dictionary safe to serialize in logs.
    """
    out = {}
    for k, v in args.items():
        # Simple types (int, str, float, bool, None) → keep original.
        if isinstance(v, (str, int, float, bool)) or v is None:
            out[k] = v
        # Short lists (<=20 elements) are fine to log.
        elif isinstance(v, list) and len(v) <= 20:
            out[k] = v
        # Otherwise replace with placeholder for the datatype.
        else:
            out[k] = f"<{type(v).__name__}>"
    return out
